import { createContext } from "react";
export const ModalContext = createContext();
export const UserDataContext = createContext();
export const CreateAccountContext = createContext();
export const ReceiptContext = createContext();
export const ViewReceiptOpenContext = createContext();
export const ProfilePicContext = createContext();
export const AppSideBarOpenContext = createContext();
export const ServiceContext = createContext();
export const PostCloseContext = createContext();